<button class="add">
    <svg class="add_icon" width="800px" height="800px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" clip-rule="evenodd" d="M11.25 12.75V18H12.75V12.75H18V11.25H12.75V6H11.25V11.25H6V12.75H11.25Z"/>
    </svg>
</button>
<script>
    const editor = document.querySelector('.add');
    editor.onclick = () =>  window.location.href = "/admin/create?name=<?= $name ?>";
</script>    