<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Магазин фото техники">
    <meta name="keywords" content="Магазин фото техники">
    <link rel="icon" href="/shared/assets/photo-camera.png" />
    <title>Кадро Магия</title>
    <link rel="stylesheet" href="/var.css">
    <link rel="stylesheet" href="/index.css">
</head>