<nav class="sidebar">
    <ul class="menu_list">
        <a class="menu_item_link" href="/">
            <li class="menu_list_item">Главная страницы</li>
        </a>
        <li class="menu_list_item dropdown_menu">
            Товары
        </li>
        <div class="dropdown">
            <a class="menu_item_link" href="/products/cameras">
                <li class="menu_list_item droped">Камеры</li>
            </a>
            <a class="menu_item_link" href="/products/lenses">
                <li class="menu_list_item droped">Объективы</li>
            </a>
            <a class="menu_item_link droped" href="/products/accessoriesAndEquipment">
                <li class="menu_list_item droped">Аксессуары и оборудование</li>
            </a>
        </div>   
        <a class="menu_item_link" href="/aboutUs">
            <li class="menu_list_item">Об авторе</li>
        </a>
        <a class="menu_item_link" href="/aboutCompany">
            <li class="menu_list_item">О фирме</li>
        </a>
    </ul>
</nav>